### ISSUE TITLE
Python PEP8

### ISSUE THREAD

**Issue by NanoDano** [linuz/TheJokerBot#3]
PEP8 is the Python accepted standard for code style. Can I modify the code to apply these standards?

The most notable changes would be:
- Tabs would be replaced with 4 spaces
- Function names will be changed from loweCamelCase to underscore_separated_words
- Top level functions will be separated by two spaces

If you use PyCharm or a vim plugin it will highlight these things for you. 

https://www.python.org/dev/peps/pep-0008/

**Comment by linuz** [comment]
Go ahead. I need to learn to follow these practices
